# Netzwerk & DNS Konfiguration
# NetworkManager für WLAN/Ethernet/VPN mit deklarativem Home-Netzwerk via sops

{ config, lib, pkgs, pkgs-unstable, ... }:

let
  # Minimales Firejail-Profil für VSCodium (Electron-kompatibel)
  vscodiumProfile = pkgs.writeText "vscodium-minimal.profile" ''
    # Minimales Firejail-Profil für VSCodium
    # Fokus auf minimale Einschränkungen für Electron-Kompatibilität

    # Home-Verzeichnis Zugriff
    noblacklist ''${HOME}
    noblacklist ''${HOME}/.config
    noblacklist ''${HOME}/.cache
    noblacklist ''${HOME}/.local
    noblacklist ''${HOME}/.vscode-oss
    noblacklist ''${HOME}/.VSCodium

    # Temporäre Dateien
    noblacklist /tmp
    noblacklist /var/tmp

    # System-Ressourcen
    noblacklist /dev
    noblacklist /sys
    noblacklist /proc
    noblacklist /run/user

    # Wayland/X11
    noblacklist /tmp/.X11-unix

    # DBus
    noblacklist /run/dbus

    # GPU/DRI
    noblacklist /dev/dri

    # Keine private Namespaces (Electron braucht Zugriff)
    ignore noroot
    ignore private-dev
    ignore private-tmp

    # Kein Seccomp (Electron-Kompatibilität)
    ignore seccomp

    # Shell-Zugriff erlauben (für integriertes Terminal)
    ignore shell none
  '';
in
{
  # ==========================================
  # NETZWERK GRUNDKONFIGURATION
  # ==========================================

  networking = {
    # Generischer Hostname (wird nicht im Netzwerk gebroadcastet)
    hostName = "nixos";
    # SICHERHEIT: IPv6 deaktiviert (verhindert VPN-Bypass und IPv6-Leaks)
    enableIPv6 = false;

    # WICHTIG: NSS/getaddrinfo soll IPv4 über IPv6 bevorzugen (da IPv6 deaktiviert)
    # Ohne dies gibt getent IPv6-Adressen zurück, die dann fehlschlagen
    getaddrinfo.precedence = {
      "::ffff:0:0/96" = 100;  # IPv4-mapped IPv6 - höchste Priorität
      "0.0.0.0/0" = 100;       # Alle IPv4-Adressen - höchste Priorität
      "::/0" = 1;              # Alle IPv6-Adressen - niedrige Priorität (deaktiviert)
    };

    # NetworkManager für alles (WLAN, Ethernet, VPN)
    networkmanager = {
      enable = true;

      # Zufällige MAC-Adresse beim Scannen (erschwert Tracking)
      wifi.scanRandMacAddress = true;
      # Zufällige MAC-Adresse bei jeder Verbindung
      wifi.macAddress = "random";
      ethernet.macAddress = "random";
      # NetworkManager nutzt systemd-resolved
      dns = "systemd-resolved";

      # ANONYMITÄT: Kein Hostname im DHCP senden
      dhcp = "internal";

      # NetworkManager Dispatcher: Hostname nicht senden
      dispatcherScripts = [
        {
          source = pkgs.writeText "no-hostname" ''
            # Verhindert, dass Hostname im DHCP gesendet wird
            if [ "$2" = "dhcp4-change" ] || [ "$2" = "dhcp6-change" ]; then
              exit 0
            fi
          '';
          type = "basic";
        }
      ];

      # Deklaratives Home-Netzwerk (wird automatisch verbunden)
      ensureProfiles = {
        environmentFiles = [ config.sops.templates."nm-wifi-env".path ];
        profiles = {
          "Greenside4" = {
            connection = {
              id = "Greenside4";
              type = "wifi";
              autoconnect = true;
              autoconnect-priority = 100;
            };
            wifi = {
              ssid = "Greenside4";
              mode = "infrastructure";
            };
            wifi-security = {
              key-mgmt = "wpa-psk";
              psk = "$WIFI_HOME_PSK";
            };
            ipv4 = {
              method = "auto";
              # CRITICAL: Ignore DHCP DNS servers, use systemd-resolved global config instead
              # Without this, router DNS (192.168.178.1) overrides Quad9 DNS-over-TLS
              # and gets blocked by firewall, breaking DNS resolution
              ignore-auto-dns = true;
            };
            ipv6 = {
              # CRITICAL: Disable IPv6 completely in NetworkManager
              # Even though kernel has disable_ipv6=1, NetworkManager's "auto" method
              # still configures IPv6 addresses via SLAAC, causing VPN leaks
              method = "disabled";
            };
          };
        };
      };
    };
  };

  # IPv6 auf Kernel-Ebene deaktivieren (zusätzliche Absicherung)
  boot.kernel.sysctl = {
    "net.ipv6.conf.all.disable_ipv6" = 1;
    "net.ipv6.conf.default.disable_ipv6" = 1;
    "net.ipv6.conf.lo.disable_ipv6" = 1;
  };

  # KRITISCH: getaddrinfo-Konfiguration um IPv6 komplett zu blockieren
  # Überschreibt die automatische NixOS-Config, da getaddrinfo.precedence nicht ausreicht
  # Ohne dies gibt getent/NSS IPv6-Adressen zurück, die dann fehlschlagen
  environment.etc."gai.conf".text = ''
    # Generated by NixOS - IPv6 disabled
    # This file configures getaddrinfo(3) to prefer IPv4 and ignore IPv6

    # Precedence: IPv4 has maximum priority (100), IPv6 minimum (1)
    precedence ::ffff:0:0/96  100  # IPv4-mapped IPv6
    precedence 0.0.0.0/0      100  # All IPv4
    precedence ::/0           1    # All IPv6 (blocked)

    # Scope: Define address scopes (not critical for our use case)
    scopev4  ::ffff:0.0.0.0/96   2
    scopev4  0.0.0.0/0           14

    reload no
  '';

  # WORKAROUND: YouTube direkt mit IPv4 in /etc/hosts (umgeht IPv6-DNS-Problem)
  networking.hosts = {
    "108.177.96.93" = [ "youtube.com" "www.youtube.com" "m.youtube.com" ];
    "142.250.185.46" = [ "googlevideo.com" ];
  };

  # ==========================================
  # DNS-OVER-TLS VIA SYSTEMD-RESOLVED
  # ==========================================

  services.resolved = {
    enable = true;

    # Quad9 DNS-over-TLS (Non-Profit, Schweizer Recht, Malware-Blocking)
    # https://www.quad9.net/service/service-addresses-and-features
    settings = {
      Resolve = {
        # DNSSEC Validation (strict enforcement)
        # "yes" = validate and FAIL resolution if validation fails
        # SECURITY: Never use "allow-downgrade" - strict validation only!
        # Note: DNSSECNegativeTrustAnchors was removed in systemd 258+
        DNSSEC = "yes";
        Domains = [ "~." ];
        DNSOverTLS = "true";
        # Primary DNS: Quad9 (Bootstrap) + Mullvad (über VPN, für Domains die Quad9 blockiert)
        # Mullvad hat keine Malware-Filterung wie Quad9, daher Quad9 first
        DNS = "9.9.9.9#dns.quad9.net 194.242.2.2#dns.mullvad.net";
        # SICHERHEIT: Kein Fallback-DNS (verhindert DNS-Leaks wenn VPN down)
        FallbackDNS = "";
        DNSStubListener = "yes";
        Cache = "no-negative";
        # SICHERHEIT: LLMNR und mDNS deaktivieren (Suricata-Warnung beheben)
        # LLMNR ist anfällig für Credential-Theft und MITM-Angriffe
        # mDNS leakt Device-Information ins lokale Netzwerk
        LLMNR = "no";
        MulticastDNS = "no";
      };
    };
  };


  # ==========================================
  # FIREJAIL SANDBOX
  # ==========================================

  # Librewolf CUSTOM minimalistisches Firejail-Profil
  # Erstellt wegen Problemen mit dem Standard-Profil und Downloads-Ordner
  environment.etc."firejail/librewolf-custom.profile".text = ''
    # Minimalistisches Firejail-Profil für LibreWolf
    # Fokus: Sicherheit ohne übermäßige Einschränkungen

    # Netzwerk
    netfilter
    protocol unix,inet,inet6,netlink

    # Capabilities einschränken
    caps.drop all

    # WICHTIG: Kein Seccomp Filter!
    # Chromium-basierte Browser (inkl. LibreWolf) brauchen bestimmte Syscalls
    # für ihren internen Sandbox. Firejail's seccomp blockiert diese und
    # zwingt den Browser, die interne Sandbox zu deaktivieren.
    # Firejail bietet bereits starke Isolation via Namespaces + AppArmor.

    # Namespaces
    nogroups
    nonewprivs
    noroot

    # CRITICAL: NO private-dev for FIDO2/WebAuthn support
    # private-dev creates isolated /dev without proper ACLs for USB HID devices
    # This breaks Nitrokey access (hidraw0 loses user:achim:rw- ACL)
    # LibreWolf has strong internal sandbox, so this is acceptable
    # Still protected by: noroot, nogroups, nonewprivs, AppArmor, netfilter
    ignore private-dev
    keep-dev-shm

    # /tmp Isolation
    private-tmp

    # Vollzugriff auf Home (KEIN private-home!)
    # Downloads, Bitwarden, etc. funktionieren ohne Whitelist-Probleme

    # D-Bus Filter
    dbus-user filter
    dbus-user.talk org.freedesktop.portal.*
    dbus-user.talk org.freedesktop.Notifications
    dbus-user.talk org.freedesktop.FileManager1
    dbus-user.talk org.gtk.vfs.*
    dbus-user.own org.mozilla.librewolf.*

    # Systemd
    dbus-system filter
    dbus-system.talk org.freedesktop.PolicyKit1

    # Shell erlauben (für Dateimanager-Start)
    # Kein "shell none"
  '';

  # Librewolf-spezifische Firejail-Konfiguration (DEPRECATED - wird nicht mehr benutzt)
  environment.etc."firejail/librewolf.local".text = ''
    # Bitwarden Desktop Native Messaging (Browser-Biometrics)
    # desktop_proxy läuft als Subprocess im Sandbox und kommuniziert
    # mit der Bitwarden Desktop-App via IPC-Socket in ~/.cache/com.bitwarden.desktop/
    ignore private-tmp
    noblacklist ''${HOME}/.librewolf/native-messaging-hosts

    # Bitwarden Desktop IPC-Socket (desktop_proxy → Desktop-App)
    noblacklist ''${HOME}/.cache/com.bitwarden.desktop
    whitelist ''${HOME}/.cache/com.bitwarden.desktop

    # Mesa Shader Cache (für GPU-Performance)
    noblacklist ''${HOME}/.cache/mesa_shader_cache
    whitelist ''${HOME}/.cache/mesa_shader_cache

    # Downloads-Ordner Zugriff (für "Im Ordner anzeigen" Funktion)
    # CRITICAL: Firejail whitelist-common.inc blockiert alles außer explizit erlaubten Ordnern
    # Wir deaktivieren die restriktiven Whitelists und erlauben Vollzugriff auf Home
    ignore include whitelist-common.inc
    ignore include whitelist-runuser-common.inc
    noblacklist ''${HOME}/Downloads
    whitelist ''${HOME}/Downloads

    # Make /run/user writable (needed for dconf and pulse)
    writable-run-user

    # PulseAudio
    ignore nosound

    # Nix-Store Zugriff für desktop_proxy Binary
    noblacklist /nix/store

    # Wayland Clipboard Zugriff (wl-copy/wl-paste für TOTP)
    # Erlaubt Paste von System-Clipboard (z.B. TOTP-Codes)
    noblacklist /run/user/1000
    whitelist /run/user/1000/wayland-*

    # D-Bus Zugriff für Bitwarden Desktop IPC und Portal-Integration
    ignore dbus-user none
    ignore dbus-system none

    dbus-user filter
    dbus-user.talk org.freedesktop.portal.*
    dbus-user.talk org.freedesktop.Notifications
    dbus-user.talk org.freedesktop.FileManager1
    dbus-user.talk org.gtk.vfs.*
    dbus-user.own org.mozilla.librewolf.*

    # System D-Bus für Polkit (Fingerprint-Authentifizierung)
    dbus-system filter
    dbus-system.talk org.freedesktop.PolicyKit1

    # FIDO2/WebAuthn Zugriff für Nitrokey (braucht /dev/hidraw*)
    ignore private-dev
    ignore nou2f

    # Dateimanager-Zugriff für "Downloads-Ordner öffnen" Funktion
    # Erlaubt das Starten von GNOME Files (Nautilus) aus der Sandbox
    ignore shell none
  '';

  # Spotify-spezifische Firejail-Konfiguration
  environment.etc."firejail/spotify.local".text = ''
    # Spotify braucht Zugriff auf eigene Binaries und Configs
    ignore private-bin
    ignore private-etc

    # D-Bus: MPRIS (Media-Controls), Notifications, Secrets (OAuth), Portal (Browser-Login)
    ignore dbus-user none
    dbus-user filter
    dbus-user.own org.mpris.MediaPlayer2.spotify
    dbus-user.talk org.freedesktop.Notifications
    dbus-user.talk org.freedesktop.secrets
    dbus-user.talk org.freedesktop.portal.*
  '';

  # Newsflash - Minimales aber sicheres Firejail-Profil
  environment.etc."firejail/newsflash-custom.profile".text = ''
    # Grundlegende Sicherheit
    caps.drop all
    nonewprivs
    noroot
    seccomp

    # Sensitive Verzeichnisse blockieren
    blacklist ''${HOME}/.ssh
    blacklist ''${HOME}/.gnupg
    blacklist /var/lib/sops-nix

    # D-Bus für Benachrichtigungen
    dbus-user filter
    dbus-user.talk org.freedesktop.Notifications
    dbus-user.talk org.freedesktop.secrets
  '';

  # Signal Desktop-spezifische Firejail-Konfiguration
  environment.etc."firejail/signal-desktop.local".text = ''
    # Signal Desktop braucht vollständigen Zugriff auf eigene Daten
    noblacklist ''${HOME}/.config/Signal
    whitelist ''${HOME}/.config/Signal

    # D-Bus für Benachrichtigungen und System-Integration
    ignore dbus-user none
    ignore dbus-system none
    dbus-user filter
    dbus-user.talk org.freedesktop.Notifications
    dbus-user.talk org.freedesktop.secrets
    dbus-user.own org.signal.*

    # Wayland Display
    noblacklist /run/user/1000
    whitelist /run/user/1000/wayland-*

    # Make /run/user writable
    writable-run-user

    # Audio
    ignore nosound

    # Private /tmp kann Probleme verursachen
    ignore private-tmp

    # Kein private-dev (für Hardware-Zugriff)
    ignore private-dev
  '';

  # Thunderbird-spezifische Firejail-Konfiguration
  environment.etc."firejail/thunderbird.local".text = ''
    # D-Bus Zugriff (erforderlich für pinentry-gnome3 und GNOME Keyring)
    ignore dbus-user none
    ignore dbus-system none

    # D-Bus Session Socket explizit whitelisten
    noblacklist /run/user/1000/bus

    dbus-user filter
    dbus-user.talk org.freedesktop.secrets
    dbus-user.talk org.gnome.keyring.*

    # Make /run/user writable (needed for dconf and pulse)
    writable-run-user

    # PulseAudio
    ignore nosound
    dbus-user.talk org.freedesktop.portal.*
    dbus-user.talk org.gtk.vfs.*
    dbus-user.own org.gnome.gcr.*

    # System D-Bus für Polkit (Smartcard-PIN-Authentifizierung)
    dbus-system filter
    dbus-system.talk org.freedesktop.PolicyKit1

    # OpenPGP/Smartcard Zugriff für Nitrokey (E-Mail-Verschlüsselung)
    # Thunderbird hat native OpenPGP-Unterstützung seit v78
    # Smartcard-Zugriff braucht /dev/hidraw* für Nitrokey
    ignore private-dev
    ignore nou2f

    # Nix-Store Zugriff für GPG-Binary und Abhängigkeiten
    noblacklist /nix/store

    # GPG-Agent Socket Zugriff für Smartcard-PIN-Eingabe
    # Socket liegt in /run/user/1000/gnupg/
    noblacklist /run/user/1000/gnupg
    whitelist /run/user/1000/gnupg

    # GPG Public Key Import (dedizierter Ordner für Key-Austausch)
    noblacklist ''${HOME}/.config/thunderbird-gpg
    whitelist ''${HOME}/.config/thunderbird-gpg

    # Thunderbird profile directory (needed for profile loading)
    noblacklist ''${HOME}/.thunderbird
    noblacklist ''${HOME}/.cache/thunderbird
    noblacklist ''${HOME}/.cache/mesa_shader_cache

    # Wayland Display Zugriff (GNOME/Wayland Session)
    # Thunderbird-Default-Profil hat "ignore include whitelist-runuser-common.inc"
    # was den Wayland-Socket blockiert. Wir aktivieren die Whitelist wieder:
    ignore ignore include whitelist-runuser-common.inc
  '';

  programs.firejail = {
    enable = true;
    wrappedBinaries = {
      tor-browser = {
        executable = "${pkgs.tor-browser}/bin/tor-browser";
        profile = "${pkgs.firejail}/etc/firejail/tor-browser_en-US.profile";
        extraArgs = [
          "--private=/home/achim/Downloads"
        ];
      };

      # Mullvad Browser - Maximum Anti-Fingerprinting (Tor Browser ohne Tor)
      # Nutzt das gleiche Firejail-Profil wie Tor Browser (technisch identisch)
      mullvad-browser = {
        executable = "${pkgs.mullvad-browser}/bin/mullvad-browser";
        profile = "${pkgs.firejail}/etc/firejail/tor-browser_en-US.profile";
        extraArgs = [
          "--private=/home/achim/Downloads"
        ];
      };

      # Signal Desktop - Messenger mit Sandbox
      signal-desktop = {
        executable = "${pkgs.signal-desktop}/bin/signal-desktop --no-sandbox";
        profile = "${pkgs.firejail}/etc/firejail/signal-desktop.profile";
      };

      # LibreWolf - Privacy Browser mit AppArmor + Firejail
      # AppArmor-Profil siehe modules/apparmor-profiles.nix
      # CUSTOM: Eigenes minimalistisches Profil wegen Download-Ordner Problemen
      librewolf = {
        executable = "${pkgs.librewolf}/bin/librewolf";
        profile = "/etc/firejail/librewolf-custom.profile";
      };

      # FreeTube - YouTube-Client mit Sandbox
      freetube = {
        executable = "${pkgs.freetube}/bin/freetube";
        profile = "${pkgs.firejail}/etc/firejail/freetube.profile";
      };

      # Thunderbird - E-Mail-Client mit Sandbox
      thunderbird = {
        executable = "${pkgs.thunderbird}/bin/thunderbird";
        profile = "${pkgs.firejail}/etc/firejail/thunderbird.profile";
      };

      # KeePassXC - Passwort-Manager mit Sandbox
      keepassxc = {
        executable = "${pkgs.keepassxc}/bin/keepassxc";
        profile = "${pkgs.firejail}/etc/firejail/keepassxc.profile";
      };

      # Newsflash - RSS-Reader mit Sandbox
      newsflash = {
        executable = "${pkgs.newsflash}/bin/io.gitlab.news_flash.NewsFlash";
        profile = "/etc/firejail/newsflash-custom.profile";
      };

      # Logseq - Wissensmanagement (Electron-App)
      # Nutzt Obsidian-Profil da kein eigenes Logseq-Profil existiert
      logseq = {
        executable = "${pkgs.logseq}/bin/logseq";
        profile = "${pkgs.firejail}/etc/firejail/obsidian.profile";
        extraArgs = [
          "--whitelist=/home/achim/Dokumente/Logseq"
        ];
      };

      # VSCodium - Code Editor (Electron-App)
      # Firejail mit deaktiviertem Electron-Sandbox (Kollision vermeiden)
      vscodium = {
        executable = "${pkgs-unstable.vscodium}/bin/codium --no-sandbox";
        extraArgs = [
          "--noprofile"             # Kein Profil verwenden (zu restriktiv für Electron)
        ];
      };

      # Evince - GNOME PDF-Viewer mit Sandbox
      evince = {
        executable = "${pkgs.evince}/bin/evince";
        profile = "${pkgs.firejail}/etc/firejail/evince.profile";
      };

      # Discord - Chat-Client mit Sandbox
      discord = {
        executable = "${pkgs.discord}/bin/discord";
        profile = "${pkgs.firejail}/etc/firejail/discord.profile";
      };

      # Flare - Signal-Client via Flatpak (eigene Bubblewrap-Sandbox)

      # Spotify - Musik-Streaming mit Sandbox
      spotify = {
        executable = "${pkgs.spotify}/bin/spotify";
        profile = "${pkgs.firejail}/etc/firejail/spotify.profile";
      };
    };
  };

  # Pakete die von Firejail gewrappt werden
  # Thunderbird: System-Paket (für Desktop-Datei) + Firejail-Wrapper (siehe wrappedBinaries oben)
  # NICHT über home-achim.nix installieren, sonst wird Wrapper überschrieben!
  # VSCodium jetzt system-level mit Firejail (Home Manager nur für Extensions/Settings)
  # (KeePassXC, Newsflash sind in home-achim.nix)
  environment.systemPackages = with pkgs; [
    tor-browser
    mullvad-browser  # Maximum Anti-Fingerprinting (Firejail-wrapped)
    librewolf
    freetube
    logseq
    discord
    spotify
    thunderbird
    signal-desktop  # Messenger (Firejail-wrapped)
    pkgs-unstable.vscodium  # VSCodium aus unstable (für aktuelle Version)
  ];
}
